modLoader = "javafml"
loaderVersion = "[47,)"
license = "LICENSE"

[[mods]]
modId = "geotectonic"
version = "${version}"
displayName = "GeoTectonic"
authors = "Alkeari"
description = ""

[[dependencies.geotectonic]]
modId = "forge"
mandatory = true
versionRange = "[47.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geotectonic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geotectonic]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "NONE"
side = "BOTH"
